---
- name: Install Redis
  apt:
    name: redis-server
    state: present

- name: Copy Redis configuration file
  ansible.builtin.template:
    src: redis.conf.j2
    dest: /etc/redis/redis.conf
  notify: restart redis-server

handlers:
  - name: restart redis-server
    ansible.builtin.service:
      name: redis-server
      state: restarted